version: "3.9"

services:
  app:
    container_name: airbnb-clone-app
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      GITHUB_ID: ${GITHUB_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
      NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET: ${NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET}
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: airbnb-clone-db
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=next-sample-db

volumes:
  mysql:
