version: "3.9"

services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: airbnb-clone-db
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=next-sample-db

  app:
    build:
      context: ./app
      target: runner
    volumes:
      - ./app:/app
    command: npm run dev
    container_name: airbnb-clone-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: development

volumes:
  mysql:
